"""
PR Review using GitHub Copilot CLI
"""

import os
import subprocess
import sys

from github import Auth, Github


def get_pr_diff(repo_name: str, pr_number: int, github_token: str):
    try:
        g = Github(auth=Auth.Token(github_token))
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(pr_number)

        diff = f"# PR #{pr_number}: {pr.title}\n\n"
        diff += f"**Description:** {pr.body or 'No description'}\n"
        changed = f"+{pr.additions} / -{pr.deletions}"
        diff += f"**Files Changed:** {pr.changed_files} ({changed})\n\n---\n\n"

        max_patch_chars = 5000
        max_total_chars = 50000
        total_chars = len(diff)
        for file in pr.get_files():
            if total_chars >= max_total_chars:
                diff += "\n... (remaining files omitted: total diff too large)"
                break
            diff += f"\n## {file.filename} ({file.status})\n"
            diff += f"+{file.additions} / -{file.deletions}\n\n"
            if file.patch:
                patch = file.patch
                remaining = max_total_chars - total_chars
                if len(patch) > min(max_patch_chars, remaining):
                    patch = patch[: min(max_patch_chars, remaining)] + "\n... (truncated)"
                diff += f"```diff\n{patch}\n```\n\n"
            total_chars = len(diff)

        return diff, pr
    except Exception as e:
        print(f"Error fetching PR: {e}")
        sys.exit(1)


def analyze_with_copilot(diff: str, github_token: str) -> str:
    prompt = f"""以下のPull Requestをレビューしてください。

レビュー観点:
1. バグ・ロジックの問題
2. セキュリティ上の懸念
3. パフォーマンス
4. Swiftベストプラクティス（Swift 6 concurrency、Actor isolation、Sendable 準拠など）
5. 良い点

---

{diff}"""

    result = subprocess.run(
        ["copilot", "--model", "gpt-5.4", "-s"],
        input=prompt,
        capture_output=True,
        text=True,
        timeout=300,
        env={**os.environ, "GITHUB_TOKEN": github_token},
    )

    if result.returncode != 0:
        print(f"Copilot CLI error: {result.stderr}")
        sys.exit(1)

    return result.stdout.strip()


def main():
    github_token = os.getenv("GITHUB_TOKEN")
    pr_number = os.getenv("PR_NUMBER")
    repository = os.getenv("REPOSITORY")
    copilot_token = os.getenv("COPILOT_GITHUB_TOKEN")

    if not all([github_token, pr_number, repository]):
        print("Missing required env vars")
        sys.exit(1)

    if not copilot_token:
        print("COPILOT_GITHUB_TOKEN is not set, skipping review")
        sys.exit(0)

    print(f"Analyzing PR #{pr_number} in {repository}")

    diff, pr = get_pr_diff(repository, int(pr_number), github_token)
    analysis = analyze_with_copilot(diff, copilot_token)

    body = f"## 🤖 Copilot Code Review\n\n{analysis}\n\n---\n*Generated by GitHub Copilot CLI (gpt-5.4)*"
    if len(body) > 65536:
        body = body[:65500] + "\n\n... (truncated: response too long)"

    existing = next(
        (c for c in pr.get_issue_comments() if "🤖 Copilot Code Review" in c.body),
        None,
    )
    if existing:
        existing.edit(body)
        print("Review updated.")
    else:
        pr.create_issue_comment(body)
        print("Review posted.")


if __name__ == "__main__":
    main()
