"""
Create or update a sticky PR comment for the generated human checklist.
"""

from __future__ import annotations

import os
import sys

from github import Auth, Github


COMMENT_MARKER = "<!-- claude-pr-human-checklist -->"
COMMENT_PATH = os.getenv("CHECKLIST_OUTPUT_PATH", ".tmp/pr-human-checklist.md")


def warn(message: str) -> None:
    print(f"::warning::{message}")


def main() -> None:
    github_token = os.getenv("GITHUB_TOKEN")
    pr_number = os.getenv("PR_NUMBER")
    repository = os.getenv("REPOSITORY")

    if not all([github_token, pr_number, repository]):
        print("Missing required env vars", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(COMMENT_PATH):
        warn(f"Checklist file not found, skipping comment update: {COMMENT_PATH}")
        sys.exit(0)

    with open(COMMENT_PATH, encoding="utf-8") as fh:
        checklist_body = fh.read().strip()

    if not checklist_body:
        warn("Checklist body is empty, skipping comment update")
        sys.exit(0)

    final_body = "\n".join(
        [
            COMMENT_MARKER,
            "## Human Review Checklist",
            "",
            checklist_body,
            "",
            "---",
            "*Generated by Claude Code Action*",
        ]
    )

    if len(final_body) > 65536:
        final_body = final_body[:65500] + "\n\n... (truncated)"

    gh = Github(auth=Auth.Token(github_token))
    repo = gh.get_repo(repository)
    pr = repo.get_pull(int(pr_number))

    existing = next(
        (comment for comment in pr.get_issue_comments() if COMMENT_MARKER in comment.body),
        None,
    )

    if existing:
        existing.edit(final_body)
        print("Checklist comment updated.")
    else:
        pr.create_issue_comment(final_body)
        print("Checklist comment posted.")


if __name__ == "__main__":
    main()
